# Pretrained models

In [ ]:
#required imports
import torch, torchvision
from tqdm.notebook import tqdm as tqdm
import matplotlib.pyplot as plt
import gzip
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import os
import zlib

from torchvision.models import resnet50, mobilenet_v2, ResNet50_Weights

In [2]:
#get weights
def get_weights(model):
    weights = []
    for param in model.parameters():
        if param.data.dim() == 4:
            w = param.data.detach().cpu().numpy()
            #round to 4 decimal places
            w = np.round(w, 4)
            weights.append(w)
        #weights.append(param.data.detach().cpu().numpy())
    return weights

In [3]:
trained = []
no_trained = []
model = mobilenet_v2(weights="IMAGENET1K_V1")
weights = get_weights(model)
print(weights[0])
for w in weights:
    cp = len(zlib.compress(w, level=9))
    ncp = len((zlib.compress(w, level=0)))
    trained.append(cp/ncp)
model = mobilenet_v2(weights=None)
weights = get_weights(model)
#print(weights[0])
for w in weights:
    cp = len(zlib.compress(w, level=9))
    ncp = len((zlib.compress(w, level=0)))
    no_trained.append(cp/ncp)

for i in range(len(trained)):
    print(no_trained[i]-trained[i])


[[[[ 1.3200e-02 -4.3000e-03  1.4800e-02]
   [ 3.2800e-02 -2.5400e-02  6.9000e-03]
   [ 1.0500e-02 -3.7300e-02 -1.4700e-02]]

  [[ 8.0000e-03 -5.9000e-03  1.5100e-02]
   [ 2.0000e-02 -3.2900e-02 -2.1000e-03]
   [ 1.1400e-02 -3.3000e-02 -7.9000e-03]]

  [[-2.5200e-02 -2.0200e-02 -1.0000e-02]
   [-1.1200e-02 -2.9300e-02 -1.5200e-02]
   [-2.6500e-02 -3.3400e-02 -2.4200e-02]]]


 [[[-6.3700e-02 -2.1300e-02  2.1400e-02]
   [ 1.3040e-01  3.7970e-01  4.2000e-02]
   [-1.8790e-01 -2.7920e-01 -3.8300e-02]]

  [[-6.7300e-02  5.3100e-02  1.8000e-03]
   [ 2.6660e-01  7.4860e-01  1.0170e-01]
   [-3.3640e-01 -6.0840e-01 -7.6800e-02]]

  [[-1.5800e-02 -1.0900e-02  2.6300e-02]
   [ 4.2100e-02  1.7310e-01  1.5000e-03]
   [-6.2100e-02 -1.5650e-01  1.0000e-03]]]


 [[[-1.0510e-01  9.7700e-02 -7.9000e-03]
   [-4.0480e-01  7.4000e-01 -3.1520e-01]
   [-6.7330e-01  9.2470e-01 -2.9980e-01]]

  [[-1.2100e-01  1.9130e-01 -4.2300e-02]
   [-8.2500e-01  1.3440e+00 -5.3650e-01]
   [-1.0619e+00  1.4805e+00 -4.7220e-01

In [24]:
model = torchvision.models.resnet18(pretrained=False)
weights = get_weights(model)
for w in weights:
    cp = len(zlib.compress(w, level=9))
    ncp = len((zlib.compress(w, level=0)))
    print(cp/ncp)

/home/infres/toyos-22/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/infres/toyos-22/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


0.9298674388332492
0.9259274327522258
0.9256833268916509
0.9265444781220122
0.9259003098788285
0.9250783188901095
0.9257798196243304
0.9286433387229629
0.9255255306163965
0.9255848647182477
0.9292561383819778
0.9291549391880524
0.9287833827893175
0.9292469083321926
0.9292706423048739
0.9257300809521075
0.9257165380277318
0.9262728883413212
0.9257524569780508
0.9257272395439035


In [9]:
#get pretrained model
model = torchvision.models.resnet18(pretrained=True)

net_ratio = []
for i in range(len(get_weights(model))):
    net_ratio.append([])


for i,w in enumerate(get_weights(model)):
    f = gzip.GzipFile('compress.gz', "w")
    np.save(file=f, arr=w)
    f.close()
    np.save('normal.npy', w)
    compressed_size = os.path.getsize('compress.gz')
    normal_size = os.path.getsize('normal.npy')
    net_ratio[i].append(compressed_size/normal_size)
    
    os.remove('compress.gz')
    os.remove('normal.npy')

/home/infres/toyos-22/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/infres/toyos-22/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [13]:
model2 = torchvision.models.resnet18(pretrained=False)
net_ratio2 = []
for i in range(len(get_weights(model2))):
    net_ratio2.append([])


for i,w in enumerate(get_weights(model2)):
    f = gzip.GzipFile('compress.gz', "w")
    np.save(file=f, arr=w)
    f.close()
    np.save('normal.npy', w)
    compressed_size = os.path.getsize('compress.gz')
    normal_size = os.path.getsize('normal.npy')
    net_ratio2[i].append(compressed_size/normal_size)
    
    os.remove('compress.gz')
    os.remove('normal.npy')

/home/infres/toyos-22/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/infres/toyos-22/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


FileNotFoundError: [Errno 2] No such file or directory: 'compress.gz'

In [14]:
!pwd

/home/infres/toyos-22
